server:
  port: 8085
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dumindanirosh/ceylontutors-config-server-store
          search-paths:
           - '*service'



